package com.idea.platform.tenant.vo;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import com.idea.platform.common.model.BaseVO;
import com.idea.platform.common.validation.Second;

import io.swagger.annotations.ApiModelProperty;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table common_user
 */
@Entity
@Table(name = "common_user")
public class CommonUser extends BaseVO implements Serializable {
	/**
	 * Database Column Remarks: id
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.id
	 *
	 * @mbg.generated
	 */
	private String id;

	/**
	 * Database Column Remarks: 商户标识码(如HRZD 华润置地)
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.code
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "租户标识码,尽可能简短并保持唯一 如HRZD 华润置地,注册必填", required = false)
	@NotBlank(message = "租户标识码不能为空", groups = {Second.class})
	@Pattern(regexp = "/^[A-Z]+$/", message = "租户标识码,尽可能简短并保持唯一 如HRZD 华润置地,注册必填", groups = {
			Second.class})

	private String code;

	/**
	 * Database Column Remarks: 商户名称
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.name
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "租户名称,注册必填", required = false)
	@NotBlank(message = "租户名称不能为空", groups = {Second.class})
	private String name;

	/**
	 * Database Column Remarks: 商户全称
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.fullName
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "租户全称,注册必填", required = false)
	@NotBlank(message = "租户全称不能为空", groups = {Second.class})
	private String fullname;

	/**
	 * Database Column Remarks: 居住地址
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.address
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "居住地址,注册必填", required = false)
	private String address;

	/**
	 * Database Column Remarks: 移动电话
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.mobile
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "移动电话,注册必填", required = false)
	private String mobile;

	/**
	 * Database Column Remarks: 电子邮箱
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.email
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "email,注册必填", required = false)
	private String email;

	/**
	 * Database Column Remarks: 法人代表
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.head
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "法人代表,注册必填", required = false)
	private String head;

	/**
	 * Database Column Remarks: 状态(0:申请中,1:审核用过)
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.status
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty(value = "当为0时可以调用审核接口", required = false)
	private Short status;

	/**
	 * Database Column Remarks: 行号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.rowNo
	 *
	 * @mbg.generated
	 */
	private Integer rowno;

	/**
	 * Database Column Remarks: 有效标记(1:有效,0:无效)
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.valid
	 *
	 * @mbg.generated
	 */
	private Short valid;

	/**
	 * Database Column Remarks: 创建者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.creator
	 *
	 * @mbg.generated
	 */
	private String creator;

	/**
	 * Database Column Remarks: 创建时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.createTime
	 *
	 * @mbg.generated
	 */
	private LocalDateTime createtime;

	/**
	 * Database Column Remarks: 修改者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.editor
	 *
	 * @mbg.generated
	 */
	private String editor;

	/**
	 * Database Column Remarks: 修改时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.editTime
	 *
	 * @mbg.generated
	 */
	private LocalDateTime edittime;

	/**
	 * Database Column Remarks: 固定电话
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column common_user.telephone
	 *
	 * @mbg.generated
	 */
	private String telephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table common_user
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.id
	 *
	 * @return the value of common_user.id
	 *
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.id
	 *
	 * @param id the value for common_user.id
	 *
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.code
	 *
	 * @return the value of common_user.code
	 *
	 * @mbg.generated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.code
	 *
	 * @param code the value for common_user.code
	 *
	 * @mbg.generated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.name
	 *
	 * @return the value of common_user.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.name
	 *
	 * @param name the value for common_user.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.fullName
	 *
	 * @return the value of common_user.fullName
	 *
	 * @mbg.generated
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.fullName
	 *
	 * @param fullname the value for common_user.fullName
	 *
	 * @mbg.generated
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname == null ? null : fullname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.address
	 *
	 * @return the value of common_user.address
	 *
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.address
	 *
	 * @param address the value for common_user.address
	 *
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.mobile
	 *
	 * @return the value of common_user.mobile
	 *
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.mobile
	 *
	 * @param mobile the value for common_user.mobile
	 *
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.email
	 *
	 * @return the value of common_user.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.email
	 *
	 * @param email the value for common_user.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.head
	 *
	 * @return the value of common_user.head
	 *
	 * @mbg.generated
	 */
	public String getHead() {
		return head;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.head
	 *
	 * @param head the value for common_user.head
	 *
	 * @mbg.generated
	 */
	public void setHead(String head) {
		this.head = head == null ? null : head.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.status
	 *
	 * @return the value of common_user.status
	 *
	 * @mbg.generated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.status
	 *
	 * @param status the value for common_user.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.rowNo
	 *
	 * @return the value of common_user.rowNo
	 *
	 * @mbg.generated
	 */
	public Integer getRowno() {
		return rowno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.rowNo
	 *
	 * @param rowno the value for common_user.rowNo
	 *
	 * @mbg.generated
	 */
	public void setRowno(Integer rowno) {
		this.rowno = rowno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.valid
	 *
	 * @return the value of common_user.valid
	 *
	 * @mbg.generated
	 */
	public Short getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.valid
	 *
	 * @param valid the value for common_user.valid
	 *
	 * @mbg.generated
	 */
	public void setValid(Short valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.creator
	 *
	 * @return the value of common_user.creator
	 *
	 * @mbg.generated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.creator
	 *
	 * @param creator the value for common_user.creator
	 *
	 * @mbg.generated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.createTime
	 *
	 * @return the value of common_user.createTime
	 *
	 * @mbg.generated
	 */
	public LocalDateTime getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.createTime
	 *
	 * @param createtime the value for common_user.createTime
	 *
	 * @mbg.generated
	 */
	public void setCreatetime(LocalDateTime createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.editor
	 *
	 * @return the value of common_user.editor
	 *
	 * @mbg.generated
	 */
	public String getEditor() {
		return editor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.editor
	 *
	 * @param editor the value for common_user.editor
	 *
	 * @mbg.generated
	 */
	public void setEditor(String editor) {
		this.editor = editor == null ? null : editor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.editTime
	 *
	 * @return the value of common_user.editTime
	 *
	 * @mbg.generated
	 */
	public LocalDateTime getEdittime() {
		return edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.editTime
	 *
	 * @param edittime the value for common_user.editTime
	 *
	 * @mbg.generated
	 */
	public void setEdittime(LocalDateTime edittime) {
		this.edittime = edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column common_user.telephone
	 *
	 * @return the value of common_user.telephone
	 *
	 * @mbg.generated
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column common_user.telephone
	 *
	 * @param telephone the value for common_user.telephone
	 *
	 * @mbg.generated
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table common_user
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CommonUser other = (CommonUser) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getFullname() == null ? other.getFullname() == null
						: this.getFullname().equals(other.getFullname()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getHead() == null ? other.getHead() == null : this.getHead().equals(other.getHead()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getRowno() == null ? other.getRowno() == null : this.getRowno().equals(other.getRowno()))
				&& (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
				&& (this.getCreator() == null ? other.getCreator() == null
						: this.getCreator().equals(other.getCreator()))
				&& (this.getCreatetime() == null ? other.getCreatetime() == null
						: this.getCreatetime().equals(other.getCreatetime()))
				&& (this.getEditor() == null ? other.getEditor() == null : this.getEditor().equals(other.getEditor()))
				&& (this.getEdittime() == null ? other.getEdittime() == null
						: this.getEdittime().equals(other.getEdittime()))
				&& (this.getTelephone() == null ? other.getTelephone() == null
						: this.getTelephone().equals(other.getTelephone()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table common_user
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getFullname() == null) ? 0 : getFullname().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getHead() == null) ? 0 : getHead().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getRowno() == null) ? 0 : getRowno().hashCode());
		result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
		result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
		result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
		result = prime * result + ((getEditor() == null) ? 0 : getEditor().hashCode());
		result = prime * result + ((getEdittime() == null) ? 0 : getEdittime().hashCode());
		result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table common_user
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", code=").append(code);
		sb.append(", name=").append(name);
		sb.append(", fullname=").append(fullname);
		sb.append(", address=").append(address);
		sb.append(", mobile=").append(mobile);
		sb.append(", email=").append(email);
		sb.append(", head=").append(head);
		sb.append(", status=").append(status);
		sb.append(", rowno=").append(rowno);
		sb.append(", valid=").append(valid);
		sb.append(", creator=").append(creator);
		sb.append(", createtime=").append(createtime);
		sb.append(", editor=").append(editor);
		sb.append(", edittime=").append(edittime);
		sb.append(", telephone=").append(telephone);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}