server:
   port: 8086

logging:
   config: classpath:log4j2-dev.xml
   
spring:
   datasource:
      url: jdbc:mysql://47.107.139.139:3306/idea_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      

   #cloud:
      #client:
         #ip-address: 172.56.33.33
                 
         
   security:     
      account:
         name: admin
         password: admin@123
   boot:
      admin:
         username: ${spring.security.account.name}
         password: ${spring.security.account.password}
      
         
manage:
   config:
      #datasoure 创建仓库--表--初始化数据
      datasource:
         url: jdbc:mysql://47.107.139.139:3306/idea_?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
         driver: com.mysql.jdbc.Driver
         username: root
         password: root
         create-database-sql: create database idea_ CHARACTER SET utf8
         create-table-sql: createtable.sql
         init-data-sql: initdata.sql
         prefix: idea_

      #mycat 修改schema.xml 重启mycat服务
      mycat:
         ip: 47.107.139.139
         port: 22
         username: root
         password: 123456
         remote: /usr/local/mycat/conf/
         filename: schema.xml
         local: D:/mycat/
         #远程服务器执行命令需要把服务器jdk环境变量改为全路径不能用%JAVA_HOME%
         command: sh /usr/local/mycat/bin/mycat restart
      
swagger:
   enable: true 

